tips:
  exit-website:
    label: ' Salir del sitio web'
    body: "Â¡Hola! ğŸ‘‹ğŸ¿ Me llamo Anya y soy la asistente virtual de EVS. ğŸ¤– No soy una persona real, solo un robot que te ayudarÃ¡ a utilizar mejor esta plataforma. Estoy aquÃ­ para ayudarte a aprender a:\r\n\r\nÂ¡Oye! Haga clic aquÃ­ para \"Salir del sitio web\" y vaya a la pÃ¡gina de inicio de Google."
  language-switcher:
    label: 'Conmutador de idioma'
  chat:
    label: 'Necesitas ayuda'
    body: 'Â¡Oye! Â¡Haga clic aquÃ­ para obtener detalles sobre recursos y soporte cerca de usted!'
