label: Contenido
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de contenido'
          separator: ', '
        name:
          label: Autor
        status:
          label: Estado
        operations:
          label: Operaciones
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: 'Tipo de contenido'
        status:
          expose:
            label: Estado
        langcode:
          expose:
            label: Idioma
      title: Contenido
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Contenido
      tab_options:
        title: Contenido
    display_title: Página
