label: 'Sub Category All Result Spanish'
display:
  default:
    display_options:
      empty:
        area:
          content:
            value: "<p>No hay contenido disponible</p>\r\n"
            format: basic_html
      header:
        result:
          content: 'TODOS LOS RESULTADOS (@total)'
      pager:
        options:
          views_infinite_scroll:
            button_text: 'Carga m√°s'
