display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        node_bulk_form:
          label: 'Formulario de operaciones masivas de nodo'
          action_title: Acción
        title:
          label: Título
          separator: ', '
        type:
          label: 'Tipo de contenido'
          separator: ', '
        name:
          separator: ', '
        operations:
          label: Operaciones
      filters:
        status:
          expose:
            label: 'Published status'
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        type:
          expose:
            label: 'Tipo de contenido'
        title:
          expose:
            label: Título
  page_1:
    display_title: Página
