module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  default_content: 0
  dynamic_page_cache: 0
  editor: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  erpw_content: 0
  erpw_custom: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  language: 0
  link: 0
  locale: 0
  mail_login: 0
  menu_item_role_access: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  search: 0
  seckit: 0
  serialization: 0
  shield: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  view_password: 0
  views_ui: 0
  content_translation: 10
  views: 10
  unicef: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  classy: 0
  erpw: 0
profile: unicef
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
