remember_domain: false
path_pages: "/admin/appearance\r\n/admin/config/system/site-information\r\n/admin/config/vss_common_config/vsscommonconfig"
_core:
  default_config_hash: PJP3-sJN2SQZTgCupMBEHry3ui7zsl93xtTovoTanFU
