_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - vss_common_config.vsscommonconfig
  - 'tour.tour.*'
  - block.block.amp_gethelp
  - block.block.amp_globalstickyblock
  - block.block.amp_servicesblock
  - block.block.amp_discoverblock
  - block.block.amp_homepagecategories
  - block.block.amp_homepageherocategoriesblock
  - block.block.amp_viewsexposedfilterblock.yml
  - block.block.amp_needhelptitle
  - block.block.iraqnavigationheadermenu.yml
  - block.block.navigationheadermenu.yml
  - 'google_*'
