module:
  acquia_connector: 0
  acquia_search: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  amp: 0
  amp_toolbar: 0
  automated_cron: 0
  autosave_form: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  color_field: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  default_content: 0
  default_content_extra: 0
  domain: 0
  domain_access: 0
  domain_config: 0
  domain_config_ui: 0
  domain_content: 0
  domain_lang: 0
  domain_language_negotiation: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_usage: 0
  environment_indicator: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  font_resize: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_gd: 0
  imageapi_optimize_tinypng: 0
  language: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_item_fields: 0
  menu_item_fields_ui: 0
  menu_link_content: 0
  menu_ui: 0
  menus_attribute: 0
  metatag: 0
  node: 0
  nodeviewcount: 0
  opigno_scorm: 0
  options: 0
  page_cache: 0
  paragraphs_edit: 0
  paragraphs_features: 0
  paragraphs_library: 0
  paragraphs_modal_edit: 0
  path: 0
  path_alias: 0
  public_preview: 0
  quick_node_clone: 0
  quickedit: 0
  rdf: 0
  schema_metatag: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_solr: 0
  seckit: 0
  serialization: 0
  shield: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tour_ui: 0
  twig_tweak: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_exposed_filter_blocks: 0
  views_infinite_scroll: 0
  views_ui: 0
  vss_common_config: 0
  vss_content: 0
  vss_custom: 0
  workflows: 0
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  paragraphs_ee: 15
  unicef: 1000
theme:
  bartik: 0
  seven: 0
  bootstrap: 0
  vss: 0
  stable: 0
  amptheme: 0
  vss_amp: 0
  adminimal_theme: 0
  vss_admin: 0
profile: unicef
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
