session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    ku: ku
    ar: ar
    '': null
  domains:
    en: ''
    es: ''
    ku: ''
    ar: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
