node_types:
  - article
  - homepage
  - podcast
  - scorm
  - video
view_modes:
  - amp
  - full
user_roles:
  - anonymous
excluded_user_roles:
  - authenticated
  - administrator
  - country_admin
  - content_editor
  - super_admin
logs_life_time: 0
_core:
  default_config_hash: Dw6pPSSwZLS5mLMTC-z_JJqKy0BXOQvDmHLMcrWfB88
