shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: vssadmin
    pass: 'Unicef#12345'
print: Hello!
allow_cli: true
_core:
  default_config_hash: yHBuI_J_kdrugm0JRNsxHODZ0qQyPzejI6r1ZPacK5Q
whitelist: ''
