favicon:
  mimetype: image/png
  path: profiles/unicef/themes/custom/vss_amp/images/favicon.png
  url: 'https://vss.lndo.site/sites/default/files/favicon_0.png'
  use_default: false
schemas:
  bootstrap: 8000
  vss: 8000
features:
  comment_user_picture: true
  comment_user_verification: true
  path: ''
  url: ''
  use_default: true
fluid_container: 1
table_responsive: '-1'
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
