label: المحتوى
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      fields:
        title:
          label: العنوان
        type:
          label: 'نوع المحتوى'
          separator: ', '
        name:
          label: المؤلف
        status:
          label: الحالة
        operations:
          label: عمليات
      filters:
        title:
          expose:
            label: العنوان
        type:
          expose:
            label: 'نوع المحتوى'
        status:
          expose:
            label: الحالة
        langcode:
          expose:
            label: اللغة
      title: المحتوى
  page_1:
    display_options:
      menu:
        title: المحتوى
      tab_options:
        title: المحتوى
    display_title: الصفحة
