label: 'Moderated content'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        title:
          label: العنوان
          separator: ', '
        type:
          label: 'نوع المحتوى'
          separator: ', '
        name:
          label: المؤلف
          separator: ', '
        moderation_state:
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        operations:
          label: عمليات
      filters:
        title:
          expose:
            label: العنوان
        type:
          expose:
            label: 'نوع المحتوى'
        langcode:
          expose:
            label: اللغة
      title: 'Moderated content'
  moderated_content:
    display_title: 'Moderated content'
