display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        media_bulk_form:
          action_title: إجراء
      filters:
        name:
          expose:
            label: الاسم
        langcode:
          expose:
            label: اللغة
      title: ميديا
  page:
    display_title: الصفحة
    display_options:
      fields:
        media_bulk_form:
          action_title: إجراء
        name:
          separator: ', '
        edit_media:
          text: تحرير
        delete_media:
          text: حذف
  widget:
    display_options:
      filters:
        name:
          expose:
            label: الاسم
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: 'النسخة المصغرة'
        name:
          label: الاسم
        uid:
          label: المؤلف
      filters:
        name:
          expose:
            label: الاسم
