display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        filename:
          label: الاسم
          separator: ', '
        filemime:
          label: 'نوع MIME'
        status:
          label: الحالة
      filters:
        filemime:
          expose:
            label: 'نوع MIME'
        status:
          expose:
            label: الحالة
  page_2:
    display_options:
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        type:
          label: 'نوع الكيان'
