description: 'Recent log messages'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        nothing:
          admin_label: Icon
        severity:
          label: Severity
        type:
          label: النوع
        timestamp:
          label: التاريخ
        message:
          label: Message
        name:
          label: المستخدم
          separator: ', '
        link:
          label: عمليات
      filters:
        type:
          expose:
            label: النوع
        severity:
          expose:
            label: Severity
      title: 'Recent log messages'
      empty:
        area:
          admin_label: 'No log messages available.'
          content: 'No log messages available.'
  page:
    display_title: الصفحة
