display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        type:
          label: النوع
        timestamp:
          label: التاريخ
        name:
          label: المستخدم
          separator: ', '
        link:
          label: عمليات
      filters:
        type:
          expose:
            label: النوع
  page:
    display_title: الصفحة
