_core:
  default_config_hash: UiTY9bhUKWJOIWDlOKM3akeeyHuJJRspXETsv3SY6jw
roles:
  service_provider_staff: perm
  service_provider_focal_point: perm
  gbv_focal_point: perm
  interagency_gbv_coordinator: perm
  country_admin: perm
