_core:
  default_config_hash: KpBeqyVjllZDDcrOdgYw6ANpzlL0LALEb8pZfegkk0M
block_inactive_users_idle_time: '12'
block_inactive_users_from_email: admin@test.com
block_inactive_users_email_content: "Hi.\r\n\r\nYour account [site-name], on has been disabled. Click here to reactivate [activation-link]."
block_inactive_users_email_subject: 'User disabled.'
block_inactive_users_include_never_accessed: false
block_inactive_users_exclude_roles: {  }
block_inactive_users_send_email: 1
