_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  acquia_connector: 0
  acquia_purge: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  administerusersbyrole: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_inactive_users: 0
  breakpoint: 0
  ckeditor: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  color_field: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  core_event_dispatcher: 0
  csp: 0
  ctools: 0
  datetime: 0
  default_content: 0
  diff: 0
  diff_moderate: 0
  domain: 0
  domain_access: 0
  domain_config: 0
  domain_config_ui: 0
  domain_content: 0
  domain_lang: 0
  domain_language_negotiation: 0
  domain_source: 0
  dynamic_page_cache: 0
  editor: 0
  email_tfa: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  erpw_content: 0
  erpw_entity_autocomplete: 0
  erpw_location: 0
  erpw_pathway: 0
  erpw_user_management: 0
  erpw_webform: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  google_tag: 0
  hal: 0
  help: 0
  history: 0
  hook_event_dispatcher: 0
  image: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  link: 0
  locale: 0
  mail_login: 0
  menu_item_role_access: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_per_role: 0
  menu_ui: 0
  menus_attribute: 0
  metatag: 0
  multiple_fields_remove_button: 0
  mysql: 0
  node: 0
  node_title_validation: 0
  node_view_permissions: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  permissions_filter: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_tokens: 0
  purge_ui: 0
  pwa: 0
  pwa_a2hs: 0
  pwa_extras: 0
  quick_node_clone: 0
  quickedit: 0
  rdf: 0
  search: 0
  seckit: 0
  serialization: 0
  shield: 0
  shortcut: 0
  simple_menu_icons: 0
  site_audit: 0
  status_messages: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_term_depth: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  unicef_iconpicker: 0
  unicef_security: 0
  user: 0
  verf: 0
  view_password: 0
  views_attach_library: 0
  views_ui: 0
  webform: 0
  webform_cards: 0
  webform_clientside_validation: 0
  webform_scheduled_email: 0
  webform_share: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  webform_workflows_element: 0
  workflow_buttons: 0
  workflows: 0
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  erpw_custom: 101
  unicef: 1000
theme:
  bartik: 0
  seven: 0
  bootstrap: 0
  stable: 0
  classy: 0
  erpw: 0
profile: unicef
