_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: c255bd80-92d8-46cc-9399-d68f7d96402c
name: 'e-Referal Pathways'
mail: no-reply@erefer.org
slogan: ''
page:
  403: ''
  404: ''
  front: /referral-pathway
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
