label: ناوەڕۆک
description: 'Find and manage content.'
display:
  default:
    display_title: Master
    display_options:
      title: ناوەڕۆک
      fields:
        title:
          label: ناونیشان
        type:
          label: 'جۆری ناوەڕۆک'
        name:
          label: نووسەر
        status:
          label: ڕەوش
          settings:
            format_custom_true: Published
        changed:
          label: Updated
        operations:
          label: کاره‌کان
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      empty:
        area_text_custom:
          content: 'No content available.'
      filters:
        title:
          expose:
            label: ناونیشان
        type:
          expose:
            label: 'جۆری ناوەڕۆک'
        status:
          expose:
            label: ڕەوش
          group_info:
            group_items:
              1:
                title: Published
        langcode:
          expose:
            label: زمان
  page_1:
    display_title: پەڕە
    display_options:
      menu:
        title: ناوەڕۆک
      tab_options:
        title: ناوەڕۆک
