description: 'Find and manage content.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        title:
          label: ناونیشان
        name:
          label: نووسەر
        status:
          label: ڕەوش
          settings:
            format_custom_true: Published
        changed:
          label: Updated
        operations:
          label: کاره‌کان
      filters:
        status:
          expose:
            label: ڕەوش
          group_info:
            group_items:
              1:
                title: Published
        type:
          expose:
            label: جۆر
        title:
          expose:
            label: ناونیشان
        langcode:
          expose:
            label: زمان
      empty:
        area_text_custom:
          content: 'No content available.'
      arguments:
        field_domain_access_target_id:
          exception:
            title: هەموو
  page_1:
    display_options:
      menu:
        title: ناوەڕۆک
      tab_options:
        title: ناوەڕۆک
      filters:
        status:
          expose:
            label: ڕەوش
          group_info:
            group_items:
              1:
                title: Published
        type:
          expose:
            label: جۆر
        title:
          expose:
            label: ناونیشان
        langcode:
          expose:
            label: زمان
      title: ناوەڕۆک
  page_2:
    display_options:
      filters:
        status:
          expose:
            label: ڕەوش
          group_info:
            group_items:
              1:
                title: Published
        type:
          expose:
            label: جۆر
        title:
          expose:
            label: ناونیشان
        langcode:
          expose:
            label: زمان
        field_domain_access_target_id:
          expose:
            label: Domain
