label: 'واژەی پۆلێن'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      arguments:
        tid:
          exception:
            title: All
  page_1:
    display_title: پەڕە
