display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        type:
          label: جۆر
        timestamp:
          label: ڕێکەوت
        name:
          label: بەکارهێنەر
        link:
          label: کاره‌کان
      filters:
        type:
          expose:
            label: جۆر
  page:
    display_title: پەڕە
