display:
  default:
    display_title: Master
    display_options:
      fields:
        info:
          label: 'Block description'
        changed:
          label: Updated
        operations:
          label: کاره‌کان
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      filters:
        info:
          expose:
            label: 'Block description'
  page_1:
    display_title: پەڕە
