display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        comment_bulk_form:
          action_title: کردار
        subject:
          label: سه‌ردیڕ
        name:
          label: نووسەر
        operations:
          label: کاره‌کان
      filters:
        subject:
          expose:
            label: سه‌ردیڕ
        langcode:
          expose:
            label: زمان
  page_unapproved:
    display_options:
      filters:
        subject:
          expose:
            label: سه‌ردیڕ
        langcode:
          expose:
            label: زمان
      fields:
        comment_bulk_form:
          action_title: کردار
        subject:
          label: سه‌ردیڕ
        name:
          label: نووسەر
        operations:
          label: کاره‌کان
