label: People
display:
  default:
    display_title: Master
    display_options:
      title: People
      fields:
        name:
          label: 'ناوی تێپەڕبوون'
        status:
          label: ڕەوش
          settings:
            format_custom_false: Blocked
            format_custom_true: چالاکە
        roles_target_id:
          label: ڕۆڵەکان
        operations:
          label: کاره‌کان
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      empty:
        area_text_custom:
          content: 'No people available.'
      filters:
        status:
          group_info:
            label: ڕەوش
            group_items:
              1:
                title: چالاکە
              2:
                title: Blocked
        roles_target_id:
          expose:
            label: Role
        permission:
          expose:
            label: Permission
      use_more_text: more
  page_1:
    display_title: پەڕە
    display_options:
      menu:
        title: List
      tab_options:
        title: People
        description: 'Manage user accounts, roles, and permissions.'
