label: بحث
display:
  default:
    display_options:
      title: بحث
      use_more_text: 'تحميل المزيد'
      header:
        result:
          content: 'جميع النتائج (@total)'
      exposed_form:
        options:
          submit_button: ' عمليات البحث الشعبية'
